apiVersion: v1
kind: Service
metadata:
  name: {{ include "turku-neural-parser.fullname" . }}
  labels:
    {{- include "turku-neural-parser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7689
      protocol: TCP
      name: http
  selector:
    {{- include "turku-neural-parser.selectorLabels" . | nindent 4 }}
