apiVersion: v1
kind: Service
metadata:
  name: {{ include "oger-so-ext.fullname" . }}
  labels:
    {{- include "oger-so-ext.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "oger-so-ext.selectorLabels" . | nindent 4 }}
